# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zyg < Formula
  desc "Professional development workflow tool for managing repositories and team collaboration"
  homepage "https://zyg.sh"
  version "0.2.1"
  license "MIT"

  depends_on "git" => :required

  on_macos do
    on_intel do
      url "https://github.com/Zyg-sh/homebrew-tap/releases/download/v0.2.1/zyg_Darwin_x86_64.tar.gz"
      sha256 "34e582926a391cbaf40519e8feeef9e46c277f23d5e1e0ef3f646987c7f8705b"

      def install
        bin.install "zyg"
        # Generate shell completions
        generate_completions_from_executable(bin/"zyg", "completion")
      end
    end
    on_arm do
      url "https://github.com/Zyg-sh/homebrew-tap/releases/download/v0.2.1/zyg_Darwin_arm64.tar.gz"
      sha256 "9556e6d4e67f66dd28e8427edb9a8799420c66abf83c2256920475ffa6152ea1"

      def install
        bin.install "zyg"
        # Generate shell completions
        generate_completions_from_executable(bin/"zyg", "completion")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Zyg-sh/homebrew-tap/releases/download/v0.2.1/zyg_Linux_x86_64.tar.gz"
        sha256 "af5282afdcb8a8b647551f53e4135feb5a2191c4add4a432330a89bd852c3d50"

        def install
          bin.install "zyg"
          # Generate shell completions
          generate_completions_from_executable(bin/"zyg", "completion")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Zyg-sh/homebrew-tap/releases/download/v0.2.1/zyg_Linux_arm64.tar.gz"
        sha256 "5b6ceafbdc6bc54167a1927d0ceb2ab2a505a648477e44282ab50694c63cec88"

        def install
          bin.install "zyg"
          # Generate shell completions
          generate_completions_from_executable(bin/"zyg", "completion")
        end
      end
    end
  end

  test do
    system "#{bin}/zyg", "version"
  end
end
