# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zyg < Formula
  desc "Professional development workflow tool for managing repositories and team collaboration"
  homepage "https://zyg.sh"
  version "0.2.2"
  license "MIT"

  depends_on "git" => :required

  on_macos do
    on_intel do
      url "https://github.com/Zyg-sh/homebrew-tap/releases/download/v0.2.2/zyg_Darwin_x86_64.tar.gz"
      sha256 "90fefaea4c83d0aaf3ea74af7aba5482b31d4098826beaf6498c620d597c21a4"

      def install
        bin.install "zyg"
        # Generate shell completions
        generate_completions_from_executable(bin/"zyg", "completion")
      end
    end
    on_arm do
      url "https://github.com/Zyg-sh/homebrew-tap/releases/download/v0.2.2/zyg_Darwin_arm64.tar.gz"
      sha256 "0fac278c07c1d1efb4f79300f249dda41faf5a070af44b8688b78a05c9a81bcf"

      def install
        bin.install "zyg"
        # Generate shell completions
        generate_completions_from_executable(bin/"zyg", "completion")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Zyg-sh/homebrew-tap/releases/download/v0.2.2/zyg_Linux_x86_64.tar.gz"
        sha256 "e7485cf692821d94642aaf2df581131b8ff667157f18ec075dd9c57e27ee2758"

        def install
          bin.install "zyg"
          # Generate shell completions
          generate_completions_from_executable(bin/"zyg", "completion")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Zyg-sh/homebrew-tap/releases/download/v0.2.2/zyg_Linux_arm64.tar.gz"
        sha256 "d7d229d6c31c5ccc120a2260effe1e88a4bee32d9a396beb2c32d8eeeb6a9b11"

        def install
          bin.install "zyg"
          # Generate shell completions
          generate_completions_from_executable(bin/"zyg", "completion")
        end
      end
    end
  end

  test do
    system "#{bin}/zyg", "version"
  end
end
